# chap15- 예외처리

## C++의 예외처리 메커니즘 : try,catch,throw
- try: 예외를 발견한다.
- catch: 예외를 잡는다.
- throw: 예외를 던진다.

#### try 블록
- try 블록 내에서 예외가 발생하면 예외처리 메커니즘에 의해서 처리됨.
```
try
{
    ...
}
```
#### catch 블록
- try블록에서 발생한 오류 처리
```
catch(처리할 예외의 종류)
{
    ...
}
```
- 무조건 try블록의 뒤에 이어서 등장해야한다. 중간에 어떤 문장이 삽입되면 안된다.
```
try
{
    ...
}
//cout << "adfasf" << endl; -> 사이에 문장이 삽입되면 안된다!
catch
{
    ...
}
```
- 받은 예외의 자료형이 다르면 실행되지 않는다.
#### throw
-  예외가 발생했음을 알리는 문장의 구성에 사용됨.
`throw expn;`
- expn은 변수,상수,객체등 모든 표현 가능한 데이터가 올수있지만, 예외상황에 대한정보를 담은 의미있는 데이터이어야 함.
- expn과 같은 예외상황을 알리는 데이터를 예외라고 한다.
- 이 문장이 실행되면 예외처리 메커니즘이 동작하여, 일반적인 프로그램의 흐름과는 다른 예외처리의 흐름이 시작됨.

#### 예외처리의 흐름
- throw에 의해 던져진 예외 데이터는, 예외 데이터를 감싸는 try 블록에 의해서 감지가 되어 이어서 등장하는 catch 블록에 의해 처리된다.
- HandlingExcpetionTryCatch.cpp 참고.
- 예외처리를 할때는 예외가 발생하면 실행되지 말아야 할 코드까지 전부 try에 넣을것

## Stack Unwinding
- throw로 예외를 발생시켰을때, 이를 처리하지 않으면, 그 함수를 호출한 영역까지 예외 데이터와 그 예외에 대한 처리의 책임까지 넘어간다.
- PassException.cpp를 참고하자.
- 여기서 알수있는 또다른점은 함수에서 함수를 호출한 영역으로 예외 데이터를 전달하면, 그 함수는 바로 종료된다는것이다.

## 하나의 try블록과 다수의 catch블록
- CatchList.cpp 참고.
- 여러 자료형을 처리하기 위해 하나의 try블록과 다수의 catch블록을 둔것을 볼수있다.

## 예외 명시
- `int ThrowFunc(int num) throw (int,char){ ... }`
- 위와같이 예외 데이터의 형을 명시할수있다. 저 원형을 보면 프로그래머는 int와 char에 대한 catch문을 작성할것이다.
- 그리고 저 함수에서 int와 char형 이외의 예외가 전달되면 프로그램을 강제 종료시킨다.
- `throw ()` 이렇게 비우면 어떤 예외도 던지지 않는다는 뜻으로, 만약 이것이 원형에 있는 함수가 예외를 발생시키면 함수를 강제종료시킨다.

## 예외 객체
- 가장 일반적인 방법.
- 예외상황을 표현하는 객체를 정의한다.
- ATMSim.cpp참고.
